### ISSUE TITLE
Ошибка в поле signature: Неверное значение поля signature

### ISSUE THREAD

**Issue by ClayRabbit** [modulbank-pay/modulbank-wordpress-shorcode#2]
```
<?php
require_once('wp-load.php');

echo do_shortcode('[modulbank_sc currency="RUB" fields="client_name,client_phone" button_text="Оплатить картой"]');
```

В тестовом режиме все ОК, в рабочем режиме после перехода на страницу оплаты выводится ошибка: "Ошибка в поле signature: Неверное значение поля signature"

В чем может быть проблема?

**Comment by VampiRUS** [comment]
При переходе в рабочий режим ключ боевой указывается?

**Comment by ClayRabbit** [comment]
Действительно забыл поменять ключ. Извиняюсь(
